# Generated by Django 6.0.6 on 2026-07-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="shop",
        ),
        migrations.AddField(
            model_name="category",
            name="shops",
            field=models.ManyToManyField(related_name="categories", to="shops.shop"),
        ),
        migrations.AddField(
            model_name="product",
            name="shops",
            field=models.ManyToManyField(related_name="products", to="shops.shop"),
        ),
    ]
