# Generated by Django 6.0.6 on 2026-07-02 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shops", "0002_remove_category_shop_category_shops_product_shops"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="description",
        ),
    ]
